Repository fontelier-AI/fontelier-ai, pull requests merged in 2024-11, with the labels that each got.

#14 Remove font
  app.py
  templates/result.html
Labels: enhancement

#19 Update README.md
  README.md
Labels: documentation

#24 fix regenerate embeddings, clear cache if regenerating
  app.py
  templates/result.html
Labels: bug

#21 Add deleted fonts history
  app.py
  templates/result.html
Labels: enhancement
